@startuml sequence colorZone
title Описание статусов обработки QR кодов продукции
legend
	Q: Oh?
	A: Ah!
end legend

participant Gray as Gr #Gray
participant Yellow as Y #Yellow
participant Green as G #LimeGreen
participant Blue as B #SkyBlue
participant White as W #White
participant Red as R #Red


==01==
==02==
==03==
@enduml