@startuml sequence definitions

skinparam {
 Roundcorner 18
 Maxmessagesize 150
 responseMessageBelowArrow true
 'backgroundColor BlanchedAlmond
 }
 
skinparam sequence {
 ArrowThickness 2
 ParticipantPadding 20
 MessageAlign center 
 }
 
box Start Wheat
	actor Оператор as Operator 
	participant Сканер as scaner 
	participant "TraceavitPro" as TA
end box

participant "Пустая канистра" as Gr #Gray
participant "Начало наполнения\n/перемещения продукта" as Y #Yellow
participant "Привязан к упаковке" as G #LimeGreen
participant "Закрытая паллета" as W #White
participant "Временное хранение" as B #SkyBlue
participant "Брак" as R #Red
participant "Suspicios" as S #Orange

autonumber 10

/'
Gr ey		- пустая канистра
Y ellow		- готова к распределению
G reen		- связана с упаковкой (ящик/поддон)
B lue		- отстой (временное хранение)
R ed		- брак
S uspicios	- подозрительные (неизвестные, исчезнувшие, потерянные и т.д.)
'/

/'
Желтый: Этап начального наполнения или перемещения продукта
в данную производственную зону из других сегментов процесса. 
Продукция может вернуться в случае повторного наполнения или инвентаризации.
Зеленый: Продукт интегрирован в свою упаковочную систему
(ящик или поддон), что свидетельствует о завершении первичной стадии упаковки.
На этом этапе коды канистр привязаны к временному коду поддона. 
Если план паллетизации предполагает ящики, то канистры привязаны к ящику,
а ящики привязаны к временному коду поддона. В случае обнаружения необходимости
доработки продукт может вернуться на стадию начального наполнения. 
сли план паллетизации предполагает ящики, то канистры привязаны к ящику, а ящики привязаны к временному коду поддона.
Белый: Продукт завершает вторичную стадию упаковки — поддон
полностью сформирован и маркирован логистической этикеткой, 
что сигнализирует об окончании производственного этапа. 
В случае необходимости паллета может быть расформирована,
и продукт возвращается на стадию начального наполнения для дальнейшей обработки.
Вторичная стадия упаковки включает сборку и маркировку поддонов, 
замену временного кода поддона на код логистической этикетки, 
что обеспечивает готовность продукции к логистическим операциям.
В отличие от этого, первичная стадия фокусируется на упаковке единиц продукции в ящики 
или на поддоны для обеспечения их безопасности и стабильности перед дальнейшей обработкой.
Красный: Продукция признана дефектной и подлежит изоляции
для последующего анализа или утилизации в соответствии с установленными процедурами
контроля качества. Данная зона является окончательной для дефектной продукции, и 
никакие дальнейшие перемещения из неё невозможны.
Голубой: Продукция временно размещена в зоне хранения для стабилизации 
или оценки качества перед дальнейшими действиями. В текущих реалиях эта зона 
используется для отстаивания канистр, например, в случае возможного запивания ножей 
или других проблем, требующих дополнительной проверки. После проверки продукция либо отправляется на упаковку (Зеленый),
либо признается дефектной и переходит в зону изоляции (Красный).

'/
@enduml
