@startuml sequence definitions

skinparam {
 Roundcorner 8
 Maxmessagesize 150
 responseMessageBelowArrow true
 backgroundColor BlanchedAlmond
 }
skinparam sequence {
 ArrowThickness 3
 ParticipantPadding 20
 MessageAlign center 
 }
 

autonumber 10 10

actor Оператор as oper
participant Сканер as scaner
participant "System" as S

box Start Wheat
  participant "Пустая канистра" as Gr #Gray
end box
box 
  participant "Начало наполнения\n/перемещения продукта" as Y #Yellow
end box
box
  participant "Привязан к упаковке" as G #LimeGreen
end box
box 
  participant "Закрытая паллета" as W #White
end box
box 
  participant "Временное хранение" as B #SkyBlue
end box
box 
  participant "Брак" as R #Red
end box
box 
  participant "Suspicios" as S #Orange
end box




/'
Желтый: Этап начального наполнения или перемещения продукта
в данную производственную зону из других сегментов процесса. 
Продукция может вернуться в случае повторного наполнения или инвентаризации.
Зеленый: Продукт интегрирован в свою упаковочную систему
(ящик или поддон), что свидетельствует о завершении первичной стадии упаковки.
На этом этапе коды канистр привязаны к временному коду поддона. 
Если план паллетизации предполагает ящики, то канистры привязаны к ящику,
а ящики привязаны к временному коду поддона. В случае обнаружения необходимости
доработки продукт может вернуться на стадию начального наполнения. 
сли план паллетизации предполагает ящики, то канистры привязаны к ящику, а ящики привязаны к временному коду поддона.
Белый: Продукт завершает вторичную стадию упаковки — поддон
полностью сформирован и маркирован логистической этикеткой, 
что сигнализирует об окончании производственного этапа. 
В случае необходимости паллета может быть расформирована,
и продукт возвращается на стадию начального наполнения для дальнейшей обработки.
Вторичная стадия упаковки включает сборку и маркировку поддонов, 
замену временного кода поддона на код логистической этикетки, 
что обеспечивает готовность продукции к логистическим операциям.
В отличие от этого, первичная стадия фокусируется на упаковке единиц продукции в ящики 
или на поддоны для обеспечения их безопасности и стабильности перед дальнейшей обработкой.
Красный: Продукция признана дефектной и подлежит изоляции
для последующего анализа или утилизации в соответствии с установленными процедурами
контроля качества. Данная зона является окончательной для дефектной продукции, и 
никакие дальнейшие перемещения из неё невозможны.
Голубой: Продукция временно размещена в зоне хранения для стабилизации 
или оценки качества перед дальнейшими действиями. В текущих реалиях эта зона 
используется для отстаивания канистр, например, в случае возможного запивания ножей 
или других проблем, требующих дополнительной проверки. После проверки продукция либо отправляется на упаковку (Зеленый),
либо признается дефектной и переходит в зону изоляции (Красный).

'/
@enduml
