@startuml login
!include https://raw.githubusercontent.com/masteroleg/uml/refs/heads/main/definitions.puml

Operator -> TA : Проверить наличие открытого поддона
alt Есть открытый поддон
    TA -> Operator : Предложить использовать открытый поддон
    Operator -> TA: Согласен
    TA -> TA : Продолжаем использовать открытый поддон
else Не согласен
    TA -> TA : Открываем новый поддон
else Нет открытого поддона
    TA -> TA : Используем новый поддон
end

@enduml