@startuml login

actor Оператор as Operator
participant Сканер as scaner
participant "System" as S

Operator -> S : Проверить наличие открытого поддона
alt Есть открытый поддон
    S -> Operator : Предложить использовать открытый поддон
    Operator -> S : Согласен
    S -> S : Продолжаем использовать открытый поддон
else Не согласен
    S -> S : Открываем новый поддон
else Нет открытого поддона
    S -> S : Используем новый поддон
end

@enduml