@startuml sequence shift-close

!include https://raw.githubusercontent.com/masteroleg/uml/refs/heads/main/definitions.puml

Operator -> TA : Решил закрыть смену
TA -> Operator : "Закрытие смены: нераспределенные канистры будут отправлены на Отстой либо в Брак. Вы уверены?"
alt Ответ: Нет
    TA -> Operator : Возврат в основной цикл производства
else Ответ: Да
    loop Пока в Нераспределенные канистры есть канистры
        Operator -> scaner : Сканировать канистру из Нераспределенные канистры
        scaner -> TA : Данные о канистре
        alt Статус: Отстой
            Y -> B: Переместить канистру на временное хранение
         else Статус: Брак
            Y -> R : Отправить канистру в Брак
        end
    end
    TA -> Operator : Нельзя закрыть смену, пока в Нераспределенные канистры есть хотя бы одна канистра
end

@enduml
