@startuml sequence shift-close

!include https://raw.githubusercontent.com/masteroleg/uml/refs/heads/main/definitions.puml

oper -> S : Решил закрыть смену
S -> oper : "Закрытие смены: нераспределенные канистры будут отправлены на Отстой либо в Брак. Вы уверены?"
alt Ответ: Нет
    S -> oper : Возврат в основной цикл производства
else Ответ: Да
    loop Пока в Нераспределенные канистры есть канистры
        oper -> scaner : Сканировать канистру из Нераспределенные канистры
        scaner -> S : Данные о канистре
        alt Статус: Отстой
            S -> B: Переместить канистру на временное хранение
         else Статус: Брак
            S -> R : Отправить канистру в Брак
        end
    end
    S -> oper : Нельзя закрыть смену, пока в Нераспределенные канистры есть хотя бы одна канистра
end

@enduml
